#!/bin/bash

set -euo pipefail

find_itp_files() {
    find . -maxdepth 1 -type f -name "*.itp" -printf "%f\n" | sort
}

has_atomtypes_section() {
    local file="$1"
    grep -qiE '^[[:space:]]*\[[[:space:]]*atomtypes[[:space:]]*\]' "$file"
}

write_include_block() {
    local top_file="$1"
    local -a atomtype_files=()
    local -a other_files=()
    local itp

    while IFS= read -r itp; do
        [[ -z "$itp" ]] && continue
        if has_atomtypes_section "$itp"; then
            atomtype_files+=("$itp")
        else
            other_files+=("$itp")
        fi
    done < <(find_itp_files)

    if [[ ${#atomtype_files[@]} -eq 0 && ${#other_files[@]} -eq 0 ]]; then
        echo -e "${ERROR}No .itp files found in the current directory. Cannot auto-generate topology.${NC}" | tee -a ./result/b_model.log >&2
        exit 1
    fi

    for itp in "${atomtype_files[@]}"; do
        printf '#include "%s"\n' "$itp" >> "$top_file"
    done
    for itp in "${other_files[@]}"; do
        printf '#include "%s"\n' "$itp" >> "$top_file"
    done
}

append_molecules_from_packmol() {
    local packmol_file="$1"
    local skip_single_electrode="$2"

    awk -v skip_single="$skip_single_electrode" '
        /^[[:space:]]*structure[[:space:]]+/ {
            molecule = $2
            next
        }
        /^[[:space:]]*number[[:space:]]+/ && molecule != "" {
            if (!(skip_single == 1 && molecule == "single_electrode.pdb")) {
                sub(/\.pdb$/, "", molecule)
                print molecule, $2
            }
            molecule = ""
        }
    ' "$packmol_file"
}

write_topology_file() {
    local top_file="$1"
    local system_name="$2"
    local packmol_file="$3"
    local skip_single_electrode="$4"
    local prepend_tmp="$5"

    cat > "$top_file" <<EOF
;
; Auto generated by build_model/source/auto_topology.sh
;

EOF

    write_include_block "$top_file"

    cat >> "$top_file" <<EOF

[ system ]
${system_name}

[ molecules ]
EOF

    if [[ "$prepend_tmp" -eq 1 ]]; then
        if [[ ! -f tmp ]]; then
            echo -e "${ERROR}tmp was not generated before writing ${top_file}.${NC}" | tee -a ./result/b_model.log >&2
            exit 1
        fi
        cat tmp >> "$top_file"
    fi

    append_molecules_from_packmol "$packmol_file" "$skip_single_electrode" >> "$top_file"
}

if [[ ! -f "${packmol}.inp" ]]; then
    echo -e "${ERROR}Missing ${packmol}.inp before topology generation.${NC}" | tee -a ./result/b_model.log >&2
    exit 1
fi

if [[ ! -f "${bulk_pa}.inp" ]]; then
    echo -e "${ERROR}Missing ${bulk_pa}.inp before topology generation.${NC}" | tee -a ./result/b_model.log >&2
    exit 1
fi

write_topology_file "${TOP}.top" "Auto generated slit system" "${packmol}.inp" 1 1
cp "${TOP}.top" "bak_${TOP}.top"

write_topology_file "${bulk_top}.top" "Auto generated bulk system" "${bulk_pa}.inp" 0 0

rm -f tmp
