#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(builtin cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
PROJECT_DIR="$(builtin cd "${SCRIPT_DIR}/.." && pwd -P)"
DRY_RUN=0
REMOVE_BIN=1
removed_count=0

usage() {
    cat <<EOF
Usage:
  bash ${SCRIPT_DIR}/clear.sh [options]

Options:
  -n, --dry-run     Print files that would be removed, but do not remove them.
  --keep-bin        Keep helper executables generated under ${PROJECT_DIR}/bin.
  -h, --help        Show this help message.
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        -n|--dry-run)
            DRY_RUN=1
            ;;
        --keep-bin)
            REMOVE_BIN=0
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "[ERROR]Unknown option: $1" >&2
            usage >&2
            exit 1
            ;;
    esac
    shift
done

load_input_file() {
    local input_file="${INPUT_FILE:-INPUT}"
    local line lhs rhs

    [[ -f "$input_file" ]] || return 0

    while IFS= read -r line || [[ -n "$line" ]]; do
        line="${line%%#*}"
        line=$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        [[ -z "$line" || "$line" != *"="* ]] && continue

        lhs="${line%%=*}"
        rhs="${line#*=}"
        lhs=$(echo "$lhs" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        rhs=$(echo "$rhs" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        [[ "$lhs" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || continue
        export "$lhs=$rhs"
    done < "$input_file"
}

log_action() {
    printf '%s\n' "$1"
}

remove_path() {
    local path

    for path in "$@"; do
        [[ -e "$path" || -L "$path" ]] || continue

        if [[ "$DRY_RUN" -eq 1 ]]; then
            log_action "[DRY-RUN] rm -rf $path"
        else
            rm -rf -- "$path"
            log_action "[CLEAR] $path"
        fi
        removed_count=$((removed_count + 1))
    done
}

remove_glob() {
    local pattern match

    for pattern in "$@"; do
        while IFS= read -r match; do
            [[ -n "$match" ]] || continue
            remove_path "$match"
        done < <(compgen -G "$pattern" || true)
    done
}

restore_file() {
    local backup="$1"
    local target="$2"

    [[ -n "$target" && -f "$backup" ]] || return 0

    if [[ "$DRY_RUN" -eq 1 ]]; then
        log_action "[DRY-RUN] cp -f $backup $target"
    else
        cp -f -- "$backup" "$target"
        log_action "[RESTORE] $target <- $backup"
    fi
}

is_safe_relative_path() {
    local path="$1"

    [[ -n "$path" ]] || return 1
    [[ "$path" != /* ]] || return 1
    [[ "$path" != *".."* ]] || return 1
    return 0
}

remove_packmol_outputs_from() {
    local inp_file="$1"
    local output_file stem

    [[ -f "$inp_file" ]] || return 0

    while IFS= read -r output_file; do
        output_file="${output_file%$'\r'}"
        is_safe_relative_path "$output_file" || continue

        remove_path "$output_file"
        if [[ "$output_file" == *.pdb ]]; then
            stem="${output_file%.pdb}"
            remove_path "${stem}s.gro"
        fi
    done < <(awk 'tolower($1) == "output" && NF >= 2 { print $2 }' "$inp_file")
}

remove_generated_frame_dirs() {
    local dir

    shopt -s nullglob
    for dir in ./*k ./*k_bulk; do
        [[ -d "$dir" ]] || continue
        if [[ -f "$dir/tandt.txt" || -f "$dir/temp.xvg" || -f "$dir/frame1.gro" ]]; then
            remove_path "$dir"
        fi
    done
    shopt -u nullglob
}

remove_autogenerated_inputs() {
    local auto_packmol_generated=0

    if [[ -n "${packmol:-}" && -f "${packmol}.inp" ]] \
        && grep -Eq "structure[[:space:]]+single_electrode[.]pdb" "${packmol}.inp"; then
        auto_packmol_generated=1
    fi

    if [[ -n "${TOP:-}" && -f "${TOP}.top" ]] \
        && grep -q "Auto generated by build_model/source/auto_topology.sh" "${TOP}.top"; then
        remove_path "${TOP}.top"
    fi

    if [[ -n "${bulk_top:-}" && -f "${bulk_top}.top" ]] \
        && grep -q "Auto generated by build_model/source/auto_topology.sh" "${bulk_top}.top"; then
        remove_path "${bulk_top}.top"
    fi

    if [[ "$auto_packmol_generated" -eq 1 ]]; then
        [[ -n "${packmol:-}" ]] && remove_path "${packmol}.inp"
        [[ -n "${bulk_pa:-}" ]] && remove_path "${bulk_pa}.inp"
    fi
}

load_input_file

if [[ -n "${TOP:-}" ]]; then
    restore_file ".top" "${TOP}.top"
fi
if [[ -n "${packmol:-}" ]]; then
    restore_file ".inp" "${packmol}.inp"
fi
restore_file "grompp_bak.mdp" "grompp.mdp"
if [[ -n "${MDP:-}" ]]; then
    restore_file "bak_${MDP}.mdp" "${MDP}.mdp"
fi

if [[ -n "${packmol:-}" ]]; then
    remove_packmol_outputs_from "${packmol}.inp"
fi
if [[ -n "${bulk_pa:-}" ]]; then
    remove_packmol_outputs_from "${bulk_pa}.inp"
fi
remove_packmol_outputs_from "bulk_.inp"
remove_packmol_outputs_from ".inp"

remove_path \
    bulk \
    build \
    nvt20 \
    initial \
    result \
    model

remove_generated_frame_dirs

remove_path \
    .step.cpt \
    .build_slit.step.cpt \
    .run_for_bulk.step.cpt \
    .top \
    .inp \
    single_electrode.pdb \
    bulk_.inp \
    index.ndx \
    mdout.mdp \
    test.log \
    tmp \
    setting.log \
    get_frame \
    grompp_bak.mdp

remove_glob \
    "./step*.pdb" \
    "./#*#" \
    "./*#" \
    "./*.top.processed" \
    "./bak_*"

remove_autogenerated_inputs

if [[ "$REMOVE_BIN" -eq 1 ]]; then
    remove_path \
        "${PROJECT_DIR}/bin/remake_packmol" \
        "${PROJECT_DIR}/bin/delete_molecules" \
        "${PROJECT_DIR}/bin/generate_slit" \
        "${PROJECT_DIR}/bin/replicate_translate" \
        "${PROJECT_DIR}/bin/double_slit_top" \
        "${PROJECT_DIR}/bin/change_name"
fi

if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "[DRY-RUN] build_model clear finished. ${removed_count} existing path(s) matched."
else
    echo "[OK]build_model generated files cleared. ${removed_count} path(s) removed or restored."
fi
